export const FETCH_MEMBERS_START = "FETCH_MEMBERS_START";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_FAIL = "FETCH_MEMBERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_TOKEN = "AUTH_TOKEN";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_FULLMEMBERS_START = "FETCH_FULLMEMBERS_START";
export const FETCH_FULLMEMBERS_SUCCESS = "FETCH_FULLMEMBERS_SUCCESS";
export const FETCH_FULLMEMBERS_FAIL = "FETCH_FULLMEMBERS_FAIL";

export const FETCH_ANNOUNCEMENTS_START = "FETCH_ANNOUNCEMENTS_START";
export const FETCH_ANNOUNCEMENTS_SUCCESS = "FETCH_ANNOUNCEMENTS_SUCCESS";
export const FETCH_ANNOUNCEMENTS_FAIL = "FETCH_ANNOUNCEMENTS_FAIL";

export const EMAIL_VERIFICATION_START = "EMAIL_VERIFFICATION_START";
export const EMAIL_VERIFICATION_SUCCESS = "EMAIL_VERIFFICATION_SUCCESS";
export const EMAIL_VERIFICATION_FAIL = "EMAIL_VERIFFICATION_FAIL";
export const EMAIL_VERIFICATION_SENT = "EMAIL_VERIFICATION_SENT";
