export const FETCH_MEMBERS_START = "FETCH_MEMBERS_START";
export const FETCH_MEMBERS_SUCCESS = "FETCH_MEMBERS_SUCCESS";
export const FETCH_MEMBERS_FAIL = "FETCH_MEMBERS_FAIL";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";

export const FETCH_FULLMEMBERS_START = "FETCH_FULLMEMBERS_START";
export const FETCH_FULLMEMBERS_SUCCESS = "FETCH_FULLMEMBERS_SUCCESS";
export const FETCH_FULLMEMBERS_FAIL = "FETCH_FULLMEMBERS_FAIL";
